### ISSUE TITLE
How do I change the sitemap dispatcher initial delay and interval?

### ISSUE THREAD

**Issue by kaifer** [edulify/play-sitemap-module.edulify.com#10]
I want to change sitemap dispatcher initial delay and interval.
Is it possible?

**Comment by eximius313** [comment]
how about adding these two properties to application.conf?

**Comment by marcospereira** [comment]
These properties are now configurable via `sitemap.initialDelay` (default to 1 minute) and `sitemap.executionInterval` (default  to 1 hour), but  these are not documented, unfortunately.

A PR is very welcome here.

**Comment by eximius313** [comment]
here you go: https://github.com/edulify/play-sitemap-module.edulify.com/pull/24

**Comment by marcospereira** [comment]
Thanks, @eximius313. I've already regenerated github pages to reflect the change made at #24.
