### ISSUE TITLE
Repository issues

### ISSUE THREAD

**Issue by dmcnelis** [edulify/play-sitemap-module.edulify.com#14]
I added the full repository information from the readme:

libraryDependencies ++= Seq(
  "com.edulify" %% "sitemapper" % "1.1.7"
)

resolvers += Resolver.url("Edulify Repository", url("http://edulify.github.io/modules/releases/"))(Resolver.ivyStylePatterns)

However, when I try to compile, I get a 404 from:
http://edulify.github.io/modules/releases/com.edulify/sitemapper/1.1.7/ivys/ivy.xml

Subsequently, my build fails from the unresolved dependency. 

Any thoughts on what I might be doing wrong?  Is there an issue with the ivy repository?

**Comment by megazord** [comment]
That is weird. Did you build.sbt sets the `scalaVersion`? It is missing part at the url. Both links bellow resolves properly:

1. http://edulify.github.io/modules/releases/com.edulify/sitemapper_2.10/1.1.7/ivys/ivy.xml
2. http://edulify.github.io/modules/releases/com.edulify/sitemapper_2.11/1.1.7/ivys/ivy.xml

Try to set a scala version and see whats happen.

**Comment by megazord** [comment]
@dmcnelis I'm closing this issue. Feel free to reopen it if you think it is necessary.
