### ISSUE TITLE
Play 2.4.0 support

### ISSUE THREAD

**Issue by mkurz** [edulify/play-sitemap-module.edulify.com#15]
Hi!

Play 2.4.0 RC2 was released already.
Could you please also release a snapshot or milestone with Play 2.4 support?

Thanks!

**Comment by megazord** [comment]
Yep. Will do it in the next few days.

**Comment by mkurz** [comment]
@megazord Cool, thanks!

**Comment by mkurz** [comment]
Play 2.4.0 was released a few hours ago :fireworks: :smile:

**Comment by mkurz** [comment]
@megazord Any ETA for 2.4 support? Thanks!

**Comment by mkurz** [comment]
Ah - just saw the 2.4 branch, so you are working on it. Sorry for anyoing you...

**Comment by mkurz** [comment]
@megazord @marcospereira Will there be a `SNAPSHOT` or even a full release soon? You need any help? Thanks!

**Comment by megazord** [comment]
@mkurz just to register that we release a 2.0.0-M1 version some hours ago.

**Comment by mkurz** [comment]
@megazord Wouldn't it be time to release the final version of `2.0.0`? Haven't had any issues so far.

**Comment by mkurz** [comment]
@marcospereira @megazord Ping :smile:

**Comment by mykhaylo-** [comment]
Hi
Are there any issues with releasing Play! 2.4.x compatible version?

**Comment by marcospereira** [comment]
@mkurz and @mykhaylo- version 2.0.0 was just released:

https://github.com/edulify/play-sitemap-module.edulify.com/releases/tag/2.0.0

Happy new year. :-)
