### ISSUE TITLE
How to access to sitemap

### ISSUE THREAD

**Issue by martinscmb** [edulify/play-sitemap-module.edulify.com#28]
Hi,

i have the version 2.0.0 in play 2.4.6 and this line not working in routes file:

> value sitemap is not a member of object com.edulify.modules.sitemap.Sitemaps

I check the Sitemaps class and the method exists.

Have you any idea about this?
![capturar](https://cloud.githubusercontent.com/assets/1194272/15188859/c67f620e-179f-11e6-89b3-d62651aaff03.PNG)

**Comment by mkurz** [comment]
I think you need to use `com.edulify.modules.sitemap.SitemapController.sitemap(suffix: String)`

**Comment by martinscmb** [comment]
It works (thank you for that)

however that class says is **deprecated**

**Comment by marcospereira** [comment]
`com.edulify.modules.sitemap.SitemapController` is the deprecated version that does not uses DI and then it is deprecated. `com.edulify.modules.sitemap.Sitemaps` is the new version that does support DI an is the recommended way to do that.
