### ISSUE TITLE
Escape & in url's

### ISSUE THREAD

**Issue by eximius313** [edulify/play-sitemap-module.edulify.com#29]
play-sitemap is not escaping ```&``` sign in URL as ```&amp;``` in XML, thus causing parser error

**Comment by mkurz** [comment]
@eximius313 Pull request welcome

**Comment by marcospereira** [comment]
Maybe this is a bug in [sitemapgen4j](https://github.com/dfabulich/sitemapgen4j/) instead since this plugins does not generated the sitemap xml directly.

I recommend you to create a isolated test case here to better figure out where is the problem.

**Comment by eximius313** [comment]
@mkurz, @marcospereira - here you have simplest test-case
Just ```sbt run``` and navigate to ```localhost:9000/sitemap.xml```
[play-java-sitemap.zip](https://github.com/edulify/play-sitemap-module.edulify.com/files/373651/play-java-sitemap.zip)

**Comment by marcospereira** [comment]
@eximius313 according to [sitemaps protocol docs](http://www.sitemaps.org/protocol.html#escaping), this should be escaped. But I believe this should be fixed at sitemapgen4j instead of here.

**Comment by eximius313** [comment]
https://github.com/dfabulich/sitemapgen4j/issues/25

**Comment by eximius313** [comment]
@marcospereira @mkurz It doesn't look like new version of sitemapgen4j will be released soon.
Are you able to merge my commit somehow?

**Comment by mkurz** [comment]
@eximius313 Sorry for the delay. I will try to release a new `sitemapgen4j` version this week.

**Comment by mkurz** [comment]
I just released 1.0.5 - it should be available within the next few hours.

**Comment by eximius313** [comment]
1.0.5 is the version of ```sitemapgen4j```, right?
```play-sitemap-module.edulify``` will be 2.1.2 ?

**Comment by mkurz** [comment]
I was talking about `sitemapgen4j` version 1.0.5 - a release of `play-sitemap-module.edulify` has to be done by @marcospereira

**Comment by marcospereira** [comment]
Version 2.1.2 was released just now. ;-)

**Comment by mkurz** [comment]
@marcospereira I also just released sitemap4j 1.0.6 with another fix https://github.com/dfabulich/sitemapgen4j/commits/master
:smile:

**Comment by eximius313** [comment]
LOL, should I wait for 2.1.3? :)

**Comment by marcospereira** [comment]
@mkurz thanks for let me know about it. :-)

@eximius313 you don't need to wait for a new release. Actually, if sitemap4j 1.0.6 is binary compatible with 1.0.5 (used by release 2.1.2), you can just add the updated dependency to your build and everything will work as expected.

**Comment by mkurz** [comment]
@eximius313 The only change in 1.0.6 is https://github.com/dfabulich/sitemapgen4j/pull/23 - if you don't need this feature you don't need to wait for the next play-sitemap version.
I released 1.0.6 shortly after 1.0.5 today because I thought if I don't release it now it probably wouldn't get released the next few month, because the project isn't that active (and I probably would forget about it).
