### ISSUE TITLE
Could not create sitemap index

### ISSUE THREAD

**Issue by n0tel** [edulify/play-sitemap-module.edulify.com#3]
When started sample application, i get the next error

```
[warn] application - Could not create sitemap index
java.lang.RuntimeException: No URLs added, sitemap index would be empty; you mus
t add some URLs with addUrls
        at com.redfin.sitemapgenerator.SitemapIndexGenerator.write(SitemapIndexG
enerator.java:203) ~[sitemapgen4j-1.0.1.jar:na]
        at com.redfin.sitemapgenerator.SitemapGenerator.writeSitemapsWithIndex(S
itemapGenerator.java:178) ~[sitemapgen4j-1.0.1.jar:na]
        at com.redfin.sitemapgenerator.WebSitemapGenerator.writeSitemapsWithInde
x(WebSitemapGenerator.java:14) ~[sitemapgen4j-1.0.1.jar:na]
        at com.edulify.modules.sitemap.SitemapJob.run(SitemapJob.java:35) ~[site
mapper_2.10-1.1.3.jar:1.1.3]
        at akka.actor.DefaultScheduler$$anon$2$$anon$5.run(Scheduler.scala:174)
~[akka-actor_2.10.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137) ~[akka
-actor_2.10.jar:na]
```

Although the site map created correctly

**Comment by taryono** [comment]
Fixed in release 1.1.7 its a playframework 2.3.x version support, I'm using playframework 2.2.1 version and using 1.1.5 version of edulify....and I found 
[warn] application - Could not create sitemap index
java.lang.RuntimeException: No URLs added, sitemap index would be empty; you mus
t add some URLs with addUrls error 
how to fix this?
please help me...

**Comment by megazord** [comment]
Hello, @taryono 

We don't have a release specific to Playframework 2.2.x. But I think you can do the following:

Configure your project to use version 1.1.5 as you already did, but excluding the sitemapgen4j dependency:

```scala
"com.edulify" %% "sitemapper" % "1.1.5" exclude("com.google.code", "sitemapgen4j")
```
Add the following dependency to your project

```scala
"com.github.dfabulich" % "sitemapgen4j" % "1.0.2"
```

This will pull the most recent version of sitemapgen4j, which corrects the behavior you are seeing.

**Comment by taryono** [comment]
Hi @megazord 

Thank you so much, it's a great solution, I have fixed the bug.....

but my header just like :

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" >

and not like an example below which there in play-sitemap-module.edulify.com-master

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://educationtous.edulify.com/wp-content/plugins/google-sitemap-generator/sitemap.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" 
xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

how to do this ?

**Comment by megazord** [comment]
Hello @taryono,

I can't understand exactly what is your problem. Where did you get that second sitemap? It looks like it wasn't generated by this plugin.

**Comment by megazord** [comment]
BTW, since there are other people subscribed to this issue, do you mind to create a new one to address your problem?
